###############################################################################
#                                  Waraos                                     # 
###############################################################################
version: '3.6'

services:

  db:
    image: mariadb:latest
    #command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mysql:/var/lib/mysql
    restart: always
    environment:
      #- MYSQL_DATABASE=${MYSQL_DATABASE}
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
      #- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - ALLOW_EMPTY_PASSWORD=yes

  webserver:
    build: ./docker
    container_name: waraos-webserver
    depends_on:
      - db
    volumes:
      - ./website:/www
    ports:
      - "8080:80"
    environment:
      #- SERVER_NAME="waraos.localhost"
      #- DVCS_HOST=${DVCS_HOST}
      #- DVCS_USER=${DVCS_USER}
      #- DVCS_REPO=${DVCS_REPO}
      #- SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      #- SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
      #- MYSQL_DATABASE=${MYSQL_DATABASE}
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
      #- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=${MYSQL_USER}
      - OPENCART_DATABASE_NAME=${MYSQL_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - ALLOW_EMPTY_PASSWORD=yes
