###############################################################################
#                                  Waraos                                     # 
###############################################################################
version: '3.6'

services:

  db:
    image: mysql:latest
    container_name: waraos-database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  webserver:
    build: ./docker
    container_name: waraos-webserver
    depends_on:
      - db
    volumes:
      - ./website:/www
    ports:
      - "8080:80"
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - DVCS_HOST=${DVCS_HOST}
      - DVCS_USER=${DVCS_USER}
      - DVCS_REPO=${DVCS_REPO}
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
